Repository ember-cli/tsconfigs, pull requests merged in 2025-04, with the labels that each got.

#1 Initial implementation
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .gitignore
  @ember/app-tsconfig/LICENSE
  @ember/app-tsconfig/README.md
  @ember/app-tsconfig/package.json
  @ember/app-tsconfig/tsconfig.json
  @ember/library-tsconfig/LICENSE
  @ember/library-tsconfig/README.md
  @ember/library-tsconfig/package.json
  @ember/library-tsconfig/tsconfig.json
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: breaking

#3 Enable `allowImportingTsExtensions` in libraries
  @ember/library-tsconfig/tsconfig.json
Labels: enhancement

#4 Clean up sourcemaps options/comments
  @ember/app-tsconfig/tsconfig.json
  @ember/library-tsconfig/tsconfig.json
Labels: documentation

#6 Add allowImportingTsExtensions to the app tsconfig
  @ember/app-tsconfig/tsconfig.json
Labels: bug

#10 Disable noPropertyAccessFromIndexSignature
  @ember/app-tsconfig/tsconfig.json
  @ember/library-tsconfig/tsconfig.json
Labels: bug

#11 For the library-tsconfig, emitDeclarationOnly + noEmit is actually required for declarations to be emitted.
  @ember/library-tsconfig/tsconfig.json
Labels: bug

#14 Remove redundant noEmits, update comments
  @ember/library-tsconfig/tsconfig.json
Labels: bug
